backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "📄 Sidor"
    files:
      - label: "🏠 Startsida"
        name: "home"
        file: "data/home.json"
        fields:
          - label: "Hero Sektion"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Huvudrubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "text"}
              - {label: "Knapptext", name: "cta_text", widget: "string"}
              - {label: "Knapplänk", name: "cta_link", widget: "string", default: "kontakt.html"}
          
          - label: "Tjänster (Översikt)"
            name: "services"
            widget: "list"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Beskrivning", name: "description", widget: "text"}
          
          - label: "Process (Översikt)"
            name: "process"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
              - label: "Steg"
                name: "steps"
                widget: "list"
                fields:
                  - {label: "Nummer", name: "number", widget: "string"}
                  - {label: "Titel", name: "title", widget: "string"}
                  - {label: "Beskrivning", name: "description", widget: "text"}
          
          - label: "Avslutande CTA"
            name: "final_cta"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
              - {label: "Knapptext", name: "button_text", widget: "string"}
              - {label: "Knapplänk", name: "button_link", widget: "string"}
      
      - label: "💼 Tjänster"
        name: "services"
        file: "data/services.json"
        fields:
          - label: "Sidinformation"
            name: "page"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
          
          - label: "Tjänster"
            name: "services"
            widget: "list"
            fields:
              - {label: "Tjänstenamn", name: "title", widget: "string"}
              - {label: "Kort beskrivning", name: "description", widget: "text"}
              - {label: "Detaljerad beskrivning", name: "details", widget: "text"}
      
      - label: "👥 Om oss"
        name: "about"
        file: "data/about.json"
        fields:
          - label: "Sidinformation"
            name: "page"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
          
          - label: "Innehåll"
            name: "content"
            widget: "object"
            fields:
              - {label: "Introduktion", name: "intro", widget: "text"}
              - {label: "Mission", name: "mission", widget: "text"}
              - {label: "Arbetssätt", name: "approach", widget: "text"}
          
          - label: "Värderingar"
            name: "values"
            widget: "list"
            fields:
              - {label: "Värdering", name: "title", widget: "string"}
              - {label: "Beskrivning", name: "description", widget: "text"}
      
      - label: "⚙️ Process"
        name: "process"
        file: "data/process.json"
        fields:
          - label: "Sidinformation"
            name: "page"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
          
          - {label: "Introduktionstext", name: "intro", widget: "text"}
          
          - label: "Faser"
            name: "phases"
            widget: "list"
            fields:
              - {label: "Nummer (t.ex. 01)", name: "number", widget: "string"}
              - {label: "Fasnamn", name: "title", widget: "string"}
              - {label: "Kort beskrivning", name: "description", widget: "text"}
              - {label: "Detaljerad beskrivning", name: "details", widget: "text"}
          
          - label: "Avslutande CTA"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
              - {label: "Knapptext", name: "button_text", widget: "string"}
              - {label: "Knapplänk", name: "button_link", widget: "string"}
      
      - label: "📧 Kontakt"
        name: "contact"
        file: "data/contact.json"
        fields:
          - label: "Sidinformation"
            name: "page"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
          
          - label: "Kontaktuppgifter"
            name: "contact_info"
            widget: "object"
            fields:
              - {label: "E-post", name: "email", widget: "string"}
              - {label: "Telefon", name: "phone", widget: "string"}
              - {label: "Adress", name: "address", widget: "string"}
          
          - label: "Formulär"
            name: "form"
            widget: "object"
            fields:
              - {label: "Rubrik", name: "title", widget: "string"}
              - {label: "Undertext", name: "subtitle", widget: "string"}
          
          - {label: "CTA-text under formulär", name: "cta_text", widget: "string"}
  
  - name: "settings"
    label: "⚙️ Inställningar"
    files:
      - label: "🏢 Företagsinformation"
        name: "company"
        file: "data/company.json"
        fields:
          - {label: "Företagsnamn", name: "name", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "E-post", name: "email", widget: "string"}
          - {label: "Telefon", name: "phone", widget: "string"}
          - {label: "Adress", name: "address", widget: "string"}
          - {label: "Copyright-text", name: "copyright", widget: "string"}
